// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package nindex

import (
	"database/sql"
)

type Note struct {
	ID         int64
	IsComplete bool
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	Note       string
}
